### ISSUE TITLE
typescript version

### ISSUE THREAD

**Issue by majkl-zumberi** [rottitime/react-hook-window-message-event#1]
this is a very useful package, but i had some issues using it in a typescript project

are you open to pull request?  i can contribute by providing a ts version of it

**Comment by rottitime** [comment]
Yes please do send over a pull request. I have not had a chance to work on this for while but open to improvements

**Comment by majkl-zumberi** [comment]
#2 this will do the job, I added a ts version of the hook

**Comment by BronyDust** [comment]
@rottitime It can be cool to use generics
@majkl-zumberi You can just add my signature to your well-documented pr

**Comment by rottitime** [comment]
@BronyDust seem to be getting conflicts. Can you rebase please and update your PR?
