### ISSUE TITLE
1.0.9 on NPM is a .ts file, vs 1.0.8

### ISSUE THREAD

**Issue by stefanvds1** [rottitime/react-hook-window-message-event#6]
https://www.npmjs.com/package/@rottitime/react-hook-message-event/v/1.0.8?activeTab=explore
vs 
https://www.npmjs.com/package/@rottitime/react-hook-message-event/v/1.0.9?activeTab=explore

should this not also be a JS file in 1.0.9 ?
i'm having issues in a non-ts project with 1.0.9

**Comment by rottitime** [comment]
@stefanvds1 support added for both JS and TS now. Please also refer to the latest [ReadMe](https://github.com/rottitime/react-hook-window-message-event) file.

The actual library broke as I accepted a PR. In future will look to add some automated checks
