### ISSUE TITLE
Example page

### ISSUE THREAD

**Issue by rottitime** [rottitime/react-hook-window-message-event#9]
Create example demo page 

e.g. https://codesandbox.io/s/brave-sea-xgop06?file=/src/Child.tsx:0-512

**Comment by chiffenok** [comment]
An example would really help. I'm trying to use the hook, but it gives me an error. I can't put around it somehow, maybe somewhere in the code I do something totally wrong but example above from codesandbox has the same error: `useMessage.ts?  Uncaught Error: Parent window has closed`. Basically what I have one parent app where I can login and I want to share an auth token to child app which is in iframe

**Comment by rottitime** [comment]
thanks @chiffenok for your message. I have updated the Readme file with a demo:
https://github.com/rottitime/react-hook-window-message-event#demo
